# devide
device: "cuda0"
datapath: "/Data4T/lf/NCT-CRC-HE-100K/NCT-CRC-HE-100K"
reload: True
# general
seed: 42
workers: 5
dataset_dir: "./datasets"

# train options
batch_size: 512
image_size: 224
start_epoch: 30
epochs: 1000
dataset: "CIFAR-10" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet

# model options
resnet: "ResNet18" # ResNet18 / ResNet34 / ResNet50
feature_dim: 512
model_path: "save"
reload: False

# loss options
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
